### ISSUE TITLE
global name 'ssl' is not defined

### ISSUE THREAD

**Issue by MustafaHalimehHH** [chaquo/chaquopy#23]
I want to use **botocore** with android, and I am getting this error:
**com.chaquo.python.PyException: NameError: global name 'ssl' is not defined**

I tried to download the source code of both packages (ssl, OpenSSL) and copy them to the python directory, but the error still exists.
Is it beause I am using python version 2.7.10 in my gradle file(python {
            version '2.7.10'}).

**Comment by mhsmith** [comment]
SSL support is missing in our current Python builds; this will be fixed in the next few days.

**Comment by mhsmith** [comment]
Fixed in Chaquopy 1.3.0.

**Comment by MustafaHalimehHH** [comment]
Thanks for your feedback.
I just want to mention that the error resolved after updating chaquopy to 1.3.0 and put the python version in the app gradle file to 2.7.14
python {
version '2.7.14'}
because the error is still exist for python version 2.7.10 even after updating chaquopy to 1.3.0.
And when I put the python version to 3.6.3 in the app gradle file I get new error:
**com.chaquo.python.PyException: SyntaxError: invalid syntax (_base.py, line 414)**
Caused by: com.chaquo.python.PyException: SyntaxError: invalid syntax (_base.py, line 414)
at <python>.load_module_impl(/data/data/com.example.halimeh.myapplication/files/chaquopy/bootstrap.zip/java/android/importer.py:180)
at <python>.load_module(/data/data/com.example.halimeh.myapplication/files/chaquopy/bootstrap.zip/java/android/importer.py:118)
at <python>._load_backward_compatible(<frozen importlib._bootstrap>:626)
at <python>._load_unlocked(<frozen importlib._bootstrap>:656)
at <python>._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
at <python>._find_and_load(<frozen importlib._bootstrap>:971)
at <python>.java.chaquopy.import_override (.c:59641)(java\import.pxi:18)
at <python>.<module>(/android_asset/chaquopy/app.zip/concurrent/futures/__init__.py:8)

I hope this will be helpful for you.

**Comment by mhsmith** [comment]
Thanks, yes, fixes to the Python builds are only made to the most recent versions of 2.7 and 3.6.

It looks like you're using your own copy of concurrent.futures. If you want to move to Python 3, this package is already in the standard library, so you should just remove it from your source code.
